nervosnetwork/ckb-sdk-swift

Source/Types/CellOutput.swift
per CKB latest renaming
For #4.
=> Change get_cells_by_type_hash cell key from outpoint to out_point

Tests/API/APIClientTests.swift, Tests/Utils/UtilsTests.swift
Also see https://github.com/nervosnetwork/ckb-demo-ruby-sdk/issues/23.
=> Update type hash

CKB.xcodeproj/project.pbxproj, Source/API/APIClient.swift, Source/Types/Script.swift, Source/Utils/Utils.swift, Tests/API/APIClientTests.swift, Tests/Types/ScriptTests.swift, Tests/Utils/UtilsTests.swift
* Get `always_success` cell hash from genesis block.
* Set and use mruby contract info (but use ruby sdk to send the cell to chain).
=> Type hashes

CKB.xcodeproj/project.pbxproj, Source/API/APIClient.swift, Source/Types/LocalNode.swift, Source/Types/TxTrace.swift, Tests/API/APIClientTests.swift
=> Implement Net & Trace RPC methods

CKB.xcodeproj/project.pbxproj, Podfile, Podfile.lock, Source/Crypto/Secp256k1.swift, Source/Utils/Utils.swift, Tests/Crypto/Secp256k1Tests.swift
* Add a C wrapper `Secp256k1` and implement `privateToPublic`.
=> Replace secp256k1_swift with secp256k1.swift

.travis.yml, CKB.xcodeproj/project.pbxproj, Package.swift, Podfile, Podfile.lock
and use beta version of CocoaPods.
=> Upgrade crypto swift to 1.0.0

Source/API/APIClient.swift, Source/Types/CellInput.swift, Source/Types/CellOutput.swift, Source/Types/Primitives.swift, Source/Types/Script.swift, Tests/API/APIClientTests.swift, Tests/Types/ScriptTests.swift, Tests/Utils/UtilsTests.swift
As per https://github.com/nervosnetwork/ckb/pull/344
Plan in `v0.9.0`.
=> Script structure refactoring

CKB.xcodeproj/project.pbxproj, Source/Types/Header.swift, Source/Types/Transaction.swift, Source/Types/Witness.swift
As per https://github.com/nervosnetwork/ckb/pull/368
=> feat: add segregated witness structure

CKB.xcodeproj/project.pbxproj, Source/Crypto/Bech32.swift, Source/Utils/AddressGenerator.swift, Source/Utils/Network.swift, Tests/Crypto/Bech32Tests.swift, Tests/Utils/AddressGeneratorTests.swift
Implement Bech32 and Address Format as per this [RFC](https://github.com/nervosnetwork/rfcs/blob/4f87099a0b1a02a8bc077fc7bea15ce3d9def120/rfcs/0000-address-format/0000-address-format.md) and this [doc](https://github.com/nervosnetwork/ckb/wiki/Common-Address-Format).
=> Address format

Source/Types/Block.swift, Source/Types/CellInput.swift, Source/Types/Header.swift, Source/Types/OutPoint.swift, Source/Types/Script.swift, Source/Utils/Utils.swift, Tests/API/APIClientTests.swift, Tests/Types/ScriptTests.swift
As per https://github.com/nervosnetwork/ckb/pull/533
=> Batch variable rename

Source/Utils/Utils.swift, Tests/Utils/UtilsTests.swift
No cell uploading and saving any more.
=> Update Utils toAddress methods to use AddressGenerator

Source/API/APIClient.swift, Source/Types/Transaction.swift, Tests/API/APIClientTests.swift
As per https://github.com/nervosnetwork/ckb/pull/566
=> Update get_transaction RPC method

Source/Types/Primitives.swift, Source/Types/Script.swift, Source/Utils/Utils.swift, Tests/Types/ScriptTests.swift, Tests/Utils/UtilsTests.swift
=> refactor: Always prefix code hash

Source/API/APIClient.swift, Source/API/APIMockingClient.swift, Source/API/APIRequest.swift, Source/API/APIResult.swift, Tests/API/APIClientTests.swift, Tests/API/RPC Fixtures/genesisBlockHash.json
=> Fix RPC request/response id unmatch issue

Source/Types/OutPoint.swift, Tests/API/APIMockingTests.swift, Tests/API/RPC Fixtures/genesisBlock.json, Tests/API/RPC Fixtures/genesisBlockHash.json
As per https://github.com/nervosnetwork/ckb/pull/620
=> Generalize OutPoint struct to reference headers

Source/API/APIClient.swift, Tests/API/APIClientTests.swift, Tests/API/APIMockingTests.swift
For https://github.com/nervosnetwork/ckb/pull/656
=> Implement get_epoch_by_number RPC method

CKB.xcodeproj/project.pbxproj, Source/API/APIClient.swift, Source/Types/ChainInfo.swift, Source/Types/PeerState.swift, Tests/API/APIClientTests.swift, Tests/API/APIMockingTests.swift, Tests/API/RPC Fixtures/blockchainInfo.json, Tests/API/RPC Fixtures/peersState.json
`get_blockchain_info` & `get_peers_state`.
=> Implement Stats RPC methods

CKB.xcodeproj/project.pbxproj, Source/API/APIClient.swift, Source/Types/DryRunResult.swift, Source/Types/Primitives.swift, Tests/API/APIClientTests.swift, Tests/API/APIMockingTests.swift, Tests/API/RPC Fixtures/computeTransactionHash.json, Tests/API/RPC Fixtures/dryRunTransaction.json
`dry_run_transaction` & `_compute_transaction_hash`.
=> Implement experiment RPC methods

Source/Utils/AddressGenerator.swift, Source/Utils/Utils.swift, Tests/Utils/AddressGeneratorTests.swift, Tests/Utils/UtilsTests.swift
Inspired by https://github.com/nervosnetwork/ckb-sdk-ruby/pull/87
=> feat: Add public key hash (blake160) to address methods

CKB.xcodeproj/project.pbxproj, Source/API/APIError.swift, Source/API/APIResult.swift, Source/Types/CellOutput.swift, Source/Types/Script.swift, Source/Utils/AddressGenerator.swift, Tests/API/APIErrorTests.swift, Tests/API/APIMockingClientTests.swift, Tests/API/APIRequestTests.swift, Tests/Types/CellInputTests.swift, Tests/Types/CellOutputTests.swift, Tests/Types/TransactionTests.swift, Tests/Types/WitnessTests.swift, Tests/Utils/AddressGeneratorTests.swift
Fix some bugs and achieve higher coverage.
=> More tests & fixes

.travis.yml, README.md, azure-pipelines.yml
Basic setup. Will squash to remove the dirty commits trying different options in the middle.
=> Set up CI with Azure Pipelines

Source/Types/Epoch.swift, Tests/API/RPC Fixtures/epoch.json
This is going to `rc/v0.15.0`.
=> feat: Update Epoch schema

.travis.yml, azure-pipelines.yml
Get ready for 24th's `v0.15.0` RC.
=> chore(ci): Modify ckb.toml to enable all RPC modules

Tests/API/RPC Fixtures/blockchainInfo.json
Ref: https://github.com/nervosnetwork/ckb/pull/1106
=> [ᚬrc/v0.15.0] chore(test): Add alert example to get_blockchain_info RPC JSON

Tests/API/RPC Fixtures/blockchainInfo.json
=> chore(test): Add alert example to get_blockchain_info RPC JSON

.travis.yml, CKB.podspec, CKB.xcodeproj/project.pbxproj, Source/Info.plist, Source/Signers/Transaction+Sign.swift, Source/Types/CellDep.swift, Source/Types/CellOutput.swift, Source/Types/Epoch.swift, Source/Types/OutPoint.swift, Source/Types/Transaction.swift, Source/Utils/SystemScript.swift, Tests/API/APIMockingTests.swift, Tests/API/RPC Fixtures/genesisBlock.json, Tests/API/RPC Fixtures/genesisBlockHash.json, Tests/API/RPC Fixtures/transaction.json, Tests/Signers/TransactionSignTests.swift, Tests/Types/CellInputTests.swift, Tests/Types/CellOutputTests.swift, Tests/Types/TransactionTests.swift, azure-pipelines.yml
- Modify transaction structure
=> Transaction structure update

Examples/Example-iOS/Example-iOS/ViewController.swift, Examples/Example-iOS/Podfile.lock, README.md
Serialize tx locally when signing.
=> docs: Update example

CKB.xcodeproj/project.pbxproj, Source/Payment/LiveCellCollector.swift, Source/Payment/Payment.swift, Source/Signers/Transaction+Sign.swift, Source/Types/CellOutput.swift, Source/Utils/AddressGenerator.swift, Source/Utils/SystemScript.swift, Source/Utils/Utils.swift, Tests/Payment/LiveCellCollectorTests.swift, Tests/Payment/PaymentTests.swift, Tests/Signers/TransactionSignTests.swift, Tests/Utils/AddressGeneratorTests.swift
Simple live cells (unspent cells) collector and payment interfaces.
TODO: update README and example - in a future PR (or directly to RC `v0.21.0` if time not allowing).
```swift
let payment = try! Payment(
from: "ckt1qyqy0frc0r8kus23ermqkxny662m37yc26fqpcyqky",
to: "ckt1qyqy0frc0r8kus23ermqkxny662m37yc26fqpcyqky",
amount: 100  * 100_000_000,
apiClient: apiClient
)
try payment.sign(privateKey: privateKey)
let txhash = try? payment.send()
```
=> Payment interface

Source/Payment/LiveCellCollector.swift, Source/Payment/Payment.swift, Tests/Payment/PaymentTests.swift
from which to scan and collect live cells as tx inputs
=> feat: Payment could be assigned a block number

CHANGELOG.md, CKB.podspec, CKB.xcodeproj/project.pbxproj, Source/Payment/LiveCellCollector.swift, Source/Payment/Payment.swift, Tests/Payment/PaymentTests.swift
* Payment could be assigned a block number ([09b94d6](https://github.com/nervosnetwork/ckb-sdk-swift/commit/09b94d6))
=> [ᚬmaster] Release v0.21.2

.travis.yml, CHANGELOG.md, CKB.podspec, CKB.xcodeproj/project.pbxproj, Examples/Example-iOS/Example-iOS/ViewController.swift, Examples/Example-iOS/Podfile.lock, Podfile.lock, azure-pipelines.yml
* CocoaPods spec ([1b2d989](https://github.com/nervosnetwork/ckb-sdk-swift/commit/1b2d989))
=> [ᚬmaster] Rc/v0.23.0

.swiftlint.yml, CKB.xcodeproj/project.pbxproj, Source/Payment/Payment.swift, Source/Serialization/BaseSerializers/ByteSerializer.swift, Source/Serialization/BaseSerializers/OptionSerializer.swift, Source/Serialization/Serializer.swift, Source/Serialization/TypeSerializers/ScriptSerializer.swift, Source/Serialization/TypeSerializers/TransactionSerializer.swift, Source/Serialization/TypeSerializers/WitnessArgsSerializer.swift, Source/Signers/Transaction+Sign.swift, Source/Types/Transaction.swift, Source/Types/WitnessArgs.swift, Tests/Serialization/BaseSerializers/DynVecSerializerTests.swift, Tests/Serialization/TypeSerializers/WitnessArgsSerializerTests.swift, Tests/Signers/TransactionSignTests.swift, Tests/Signers/WitnessArgsTests.swift
Please note this doesn't take care of multiple input groups.
=> feat: Implement WitnessArgs and its serializer

.travis.yml, CHANGELOG.md, CKB.podspec, CKB.xcodeproj/project.pbxproj, Examples/Example-iOS/Podfile.lock, README.md, Source/Utils/AddressGenerator.swift, Tests/Utils/AddressGeneratorTests.swift, azure-pipelines.yml
* Limit address generator to support short payload format version ([0e5d410](https://github.com/nervosnetwork/ckb-sdk-swift/commit/0e5d410))
=> [ᚬmaster] Rc/v0.25.0
